name: recogbase
version: 1.2.1
date: 31/04/2014
description: A framework for group recognition

authors:
    - name: Max Neunhoeffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef/
    - name: Akos Seress
      url: http://www.math.ohio-state.edu/~akos/

GAP: ">=4.4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
    - name: "Forms"
      version: ">= 1.2"
    - name: "genss"
      version: ">= 1.3"
    - name: "Orb"
      version: ">= 3.4"
    - name: "FactInt"
      version: ">= 1.5.2"
    - name: "AtlasRep"
      version: ">= 1.4.0"

suggested-pkgs:
    - name: "recog"
      version: ">= 1.0"

www: http://neunhoef.github.io/recogbase/
readme: http://neunhoef.github.io/recogbase/README
packageinfo: http://neunhoef.github.io/recogbase/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/neunhoef/recogbase/releases/download/v1.2.1/recogbase-1.2.1.tar.gz
    - name: .tar.bz2
      url: https://github.com/neunhoef/recogbase/releases/download/v1.2.1/recogbase-1.2.1.tar.bz2

abstract: <b>Warning:</b> This package is still under development and this version is to be considered a working, but preliminary one. <p/> This package provides a framework to implement group recognition methods in a generic way. In particular, it is suitable for permutation groups, matrix groups, projective groups and blackbox groups. The accompanying <span class="pkgname">recog</span> package contains the necessary methods for actual recognition.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
