name: recogbase
version: 1.2.4
date: 07/01/2016
description: A framework for group recognition

authors:
    - name: Max Neunhöffer
      url: http://www-groups.mcs.st-and.ac.uk/~neunhoef
    - name: Ákos Seress

maintainers:
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">=4.7.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Forms"
      version: ">= 1.2"
      url: "http://cage.ugent.be/geometry/forms.php"
    - name: "genss"
      version: ">= 1.3"
      url: "http://gap-packages.github.io/genss/"
    - name: "Orb"
      version: ">= 3.4"
      url: "http://gap-packages.github.io/orb/"
    - name: "FactInt"
      version: ">= 1.5.2"
      url: "http://www.gap-system.org/DevelopersPages/StefanKohl/factint.html"
    - name: "AtlasRep"
      version: ">= 1.4.0"
      url: "http://www.math.rwth-aachen.de/~Thomas.Breuer/atlasrep"

suggested-pkgs:
    - name: "recog"
      version: ">= 1.2.4"
      url: "http://gap-packages.github.io/recog/"

www: http://gap-packages.github.io/recogbase/
readme: http://gap-packages.github.io/recogbase/README
packageinfo: http://gap-packages.github.io/recogbase/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/recogbase/releases/download/v1.2.4/recogbase-1.2.4.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/recogbase/releases/download/v1.2.4/recogbase-1.2.4.tar.bz2

abstract: <b>Warning:</b> This package is still under development and this version is to be considered a working, but preliminary one. <p/> This package provides a framework to implement group recognition methods in a generic way. In particular, it is suitable for permutation groups, matrix groups, projective groups and blackbox groups. The accompanying <span class="pkgname">recog</span> package contains the necessary methods for actual recognition.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
